name: deploy .NET Core application to Web App MySelfStudyApp
on:
    push:
        branches:
        - main
        
env:
  AZURE_WEBAPP_NAME: MySelfStudyApp
  AZURE_WEBAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: ./MySelfStudyApp
jobs:
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.MySelfStudyApp_1522 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
